import type { Metadata } from "next";
import { ThemeModeScript } from "flowbite-react";
import "./globals.css";

export const metadata: Metadata = {
  title: "OpenWarnDE",
  description: "Generated by some kid :==)",
  icons: {
    icon: "/icon.png",
    shortcut: "/icon.png",
    apple: "/icon.png",
  },

  openGraph: {
    title: "OpenWarnDE",
    description: "Made by a random kid before turning 20. Somehow it works.",
    url: "https://openwarnde.web.app/",
    siteName: "OpenWarnDE",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de" suppressHydrationWarning className="h-full w-full">
      <head>
        <ThemeModeScript />
        <link rel="icon" href="/icon.png" type="image/png" />
        <link rel="apple-touch-icon" href="/icon.png" />
      </head>
      <body className="h-full w-full flex flex-col antialiased bg-gray-100 dark:bg-gray-900">
        {children}
      </body>
    </html>
  );
}